/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  content_banner: () => import("@/views/content/banner/index.vue"),
  content_notice: () => import("@/views/content/notice/index.vue"),
  content_shop: () => import("@/views/content/shop/index.vue"),
  goods_category: () => import("@/views/goods/category/index.vue"),
  goods_inventory: () => import("@/views/goods/inventory/index.vue"),
  goods_list: () => import("@/views/goods/list/index.vue"),
  home: () => import("@/views/home/index.vue"),
  order: () => import("@/views/order/index.vue"),
  refund: () => import("@/views/refund/index.vue"),
  system_account: () => import("@/views/system/account/index.vue"),
  system_config: () => import("@/views/system/config/index.vue"),
  system_log: () => import("@/views/system/log/index.vue"),
  system_user: () => import("@/views/system/user/index.vue"),
};
