/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'content',
    path: '/content',
    component: 'layout.base',
    meta: {
      title: 'content',
      i18nKey: 'route.content',
      icon: 'mdi:view-dashboard-variant-outline',
      order: 5
    },
    children: [
      {
        name: 'content_banner',
        path: '/content/banner',
        component: 'view.content_banner',
        meta: {
          title: 'content_banner',
          i18nKey: 'route.content_banner',
          icon: 'mdi:view-carousel-outline',
          order: 1
        }
      },
      {
        name: 'content_notice',
        path: '/content/notice',
        component: 'view.content_notice',
        meta: {
          title: 'content_notice',
          i18nKey: 'route.content_notice',
          icon: 'mdi:bullhorn-outline',
          order: 3
        }
      },
      {
        name: 'content_shop',
        path: '/content/shop',
        component: 'view.content_shop',
        meta: {
          title: 'content_shop',
          i18nKey: 'route.content_shop',
          icon: 'mdi:store-outline',
          order: 2
        }
      }
    ]
  },
  {
    name: 'goods',
    path: '/goods',
    component: 'layout.base',
    meta: {
      title: 'goods',
      i18nKey: 'route.goods',
      icon: 'mdi:food-apple-outline',
      order: 2
    },
    children: [
      {
        name: 'goods_category',
        path: '/goods/category',
        component: 'view.goods_category',
        meta: {
          title: 'goods_category',
          i18nKey: 'route.goods_category',
          icon: 'mdi:file-tree-outline',
          order: 2
        }
      },
      {
        name: 'goods_inventory',
        path: '/goods/inventory',
        component: 'view.goods_inventory',
        meta: {
          title: 'goods_inventory',
          i18nKey: 'route.goods_inventory',
          icon: 'mdi:package-variant-closed',
          order: 3
        }
      },
      {
        name: 'goods_list',
        path: '/goods/list',
        component: 'view.goods_list',
        meta: {
          title: 'goods_list',
          i18nKey: 'route.goods_list',
          icon: 'mdi:noodles',
          order: 1
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'order',
    path: '/order',
    component: 'layout.base$view.order',
    meta: {
      title: 'order',
      i18nKey: 'route.order',
      icon: 'mdi:clipboard-list-outline',
      order: 3
    }
  },
  {
    name: 'refund',
    path: '/refund',
    component: 'layout.base$view.refund',
    meta: {
      title: 'refund',
      i18nKey: 'route.refund',
      icon: 'mdi:cash-refund',
      order: 4
    }
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'mdi:cog-outline',
      order: 9
    },
    children: [
      {
        name: 'system_account',
        path: '/system/account',
        component: 'view.system_account',
        meta: {
          title: 'system_account',
          i18nKey: 'route.system_account',
          icon: 'mdi:account-cog-outline',
          order: 1
        }
      },
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config',
          icon: 'mdi:tune-variant',
          order: 3
        }
      },
      {
        name: 'system_log',
        path: '/system/log',
        component: 'view.system_log',
        meta: {
          title: 'system_log',
          i18nKey: 'route.system_log',
          icon: 'mdi:script-text-outline',
          order: 2
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user',
          icon: 'mdi:account-group-outline',
          order: 4
        }
      }
    ]
  }
];
